### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by mannyamorim** [karansher/computer-graphics-ray-tracing#2]
A couple of clarifications for assignment 3:

1. Should we be using the I/(r^2) to attenuate the light intensity? It seems that when I add this to my raytracer, the point lights become so dim that they have no effect. Want to check if this is something we should be including in this assignment.
2. Should we be adding ambient light? I know that in `Material.h` we have the `ka` coefficient however I don't see any global ambient light intensity to multiply by to find the ambient light. Also if I add the `ka` directly (assuming that the ambient light coefficient is 1.0) then the images become much brighter than the samples. Want to know if ambient light is something we are considering for this assignment.
3. How many bounces should be done for the reflected rays? Is this number up to us, or is there a specific value we should be using. From my tests, using 5 bounces, I was able to simulate the sample images, would like to know if this is ok.

**Comment by horacelynn** [comment]
For q2, it mentions that we use a hardcoded ambient light coefficient of 0.1 in blinn_phong_shading.h

**Comment by DerekCresswell** [comment]
For q1, I recall the prof mentioning that in such small scenes, dealing with light falloff just makes things too dim so we forego using it.
