### ISSUE TITLE
Unable to render bunny

### ISSUE THREAD

**Issue by RamDaj** [karansher/computer-graphics-ray-tracing#23]
Hello, for some reason, I'm able to render any of the provided json files, however when I try to render bunny.json, I'm immediately met with an error. I'm pretty confused as I don't think I did anything wrong, FYI I'm on windows.

![Error](https://user-images.githubusercontent.com/59125095/193476835-899d84fd-39e8-4d03-b6af-e47c72ca4ad6.png)

**Comment by panuelosj** [comment]
The filepath might be off by a folder, try checking the bunny.json file and see if the reference for bunny.stl points to the right file (you might need to add an extra ../ or something like that)

**Comment by RamDaj** [comment]
That seemed to be the issue, I just added a "../data/" before and it seems to have done the trick, thanks!
