### ISSUE TITLE
specular shading viewer vector

### ISSUE THREAD

**Issue by yuetsai93** [karansher/computer-graphics-ray-tracing#25]
When calculating specular shading using h, v and l are involved. I understood how to calculate l, it's basically the direction vector towards the light. But I'm quite confused about how should I get v here. Are we given the viewer's position? Am I missing something here? Thanks in advance.
![IMG_6AFD73A446C6-1](https://user-images.githubusercontent.com/53865015/193505629-debcf128-7572-4efe-bea3-c9c3f6125ab4.jpeg)

**Comment by panuelosj** [comment]
v is the input ray vector, whatever vector is intersecting the surface. This could be the cast vector from the eye, but could also be a reflected vector from another surface.
