### ISSUE TITLE
IOError: .\bunny.stl could not be opened...

### ISSUE THREAD

**Issue by fares-soliman** [karansher/computer-graphics-ray-tracing#32]
Hello,

Getting the error in the title when I try to render bunny.json.

My ray-casting lab does not have this problem, and I can open the bunny.stl just fine on windows. I tried re-cloning, same error.

Any help is appreciated.

**Comment by mehagupta22** [comment]
Hey! I had the same issue - fixed it by following solution from #8

**Comment by fares-soliman** [comment]
Oh, I see, thanks!
