### ISSUE TITLE
Shading of Spheres Packing

### ISSUE THREAD

**Issue by JanardanS** [karansher/computer-graphics-ray-tracing#6]
Spheres and two spheres on planes have shading on the plane. However, packing spheres for some reason doesn't shade the plane black. Everything else works, and I am not sure what's wrong with it.

![image](https://user-images.githubusercontent.com/35342648/192905123-e57ea413-7785-4cc0-99c6-7aa55e4426f9.png)

**Comment by Macdeini** [comment]
I'm having the same issue, where the floor shadows for sphere packing arent appearing, but im getting the proper results for sphere-and-plane
![image](https://user-images.githubusercontent.com/84424393/193163939-2539b4fa-dd31-4125-93d8-a69d7e252055.png)
![image](https://user-images.githubusercontent.com/84424393/193163989-472bb0aa-308e-48fb-ba8f-aeff461aa5cc.png)

**Comment by JanardanS** [comment]
I just fixed the issue. The problem I had was I normalized the vector light direction before calling hit, when I never normalized point lights. So you can normalize all directions in your code and stay constistent, that should fix it, or you normalize right before calculating colours.
