### ISSUE TITLE
IO Error

### ISSUE THREAD

**Issue by calebxcaleb** [karansher/computer-graphics-ray-tracing#8]
When I try to test my program on the bunny.json file (and other files that require stl files) I get an IO Erro like the following 
![image](https://user-images.githubusercontent.com/43897989/192933169-4df5b5ea-4251-4a1b-ada7-fd99313c0f26.png)
I could run bunny.json on A2 but for A3 I can not for some reason. Would anyone know of a fix or something I can look further into so that I could fix this issue? Thanks!!

**Comment by JanardanS** [comment]
You have to modify the json file where it says bunny stl to what u have in ur main file. For me ..\data\bunny.stl was good enough, but i think others might have to do ..\..\data\bunny.stl.

**Comment by calebxcaleb** [comment]
It worked with ../data/bunny.stl

Thanks!!
